package org.uob.a2.model;

/*
    this enum lists all resource types used in the simulation.
    using an enum is useful because:
    - it guarantees only valid resources exist
    - it keeps resource names consistent everywhere
    - it makes the inventory map simple and safe to use

    each constant represents a type of resource the colony can produce,
    consume, convert, or store during the simulation.
*/
public enum ResourceType {

    // raw materials gathered from basic producers
    ORE,
    METAL,

    // currency used for building structures
    CREDITS,

    // power generated by solar farms and used for operations
    ENERGY,

    // food for supporting population growth
    FOOD,

    // water for farms or building costs
    WATER,

    // extracted gas used for reactor fuel conversion
    GAS,

    // advanced fuel created by reactors
    FUEL,

    // total people in the colony (used for crew)
    POPULATION
}
